version: '3'
services:

  country-be:
    image: "andreyley/country_proxy:1.0.1"
    environment:
      - CASH_HOST=redis
      - CASH_PORT=6379
    ports:
      - "5000:80"
    links:
      - "redis"
    networks:
      - country-information-network
    depends_on:
      - redis
    restart: always
    
  redis:
    image: "redis:alpine"
    ports:
      - "5001:6379"
    networks:
      - country-information-network
    restart: always
      
# network_mode: none
networks:
  country-information-network:
    ipam:
      driver: default
      config:
        - subnet: 10.171.0.0/24        
  
        